input_lvs = [
    {
        'X': (1, 12),
        'name': 'Communication',
		'terms': {
			'Ineffective': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'Average': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'Effective': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'Exceptional': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
		}
    },

    {
        'X': (1, 12),
        'name': 'Professional skills',
        'terms': {
			'Inadequate': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
			'Basic': {'umf': ('trapmf', 0.42, 2.25, 4., 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 3.71, 0.34)},
			'Competent': {'umf': ('trapmf', 1.59, 2.75, 4.35, 6.26), 'lmf': ('trapmf', 2.79, 3.34, 3.34, 3.67, 0.35)},
			'Advanced': {'umf': ('trapmf', 3.38, 5.5, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 6.67, 0.33)},
			'Expert': {'umf': ('trapmf', 4.59, 5.9, 7.25, 8.5), 'lmf': ('trapmf', 6.29, 6.67, 6.67, 7.17, 0.39)},
			'Professional': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (1, 12),
        'name': 'Leadership',
		'terms': {
			'Lack': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
			'Limited': {'umf': ('trapmf', 0.42, 2.25, 4., 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 3.71, 0.34)},
			'Moderate': {'umf': ('trapmf', 1.59, 2.75, 4.35, 6.26), 'lmf': ('trapmf', 2.79, 3.34, 3.34, 3.67, 0.35)},
			'Effective': {'umf': ('trapmf', 3.38, 5.5, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 6.67, 0.33)},
			'Strong': {'umf': ('trapmf', 4.59, 5.9, 7.25, 8.5), 'lmf': ('trapmf', 6.29, 6.67, 6.67, 7.17, 0.39)},
			'Exceptional': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
		}
    },

    {
        'X': (1, 12),
        'name': 'Adaptability',
        'terms': {
            'Limited': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'Moderate': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'Good': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'Exceptional': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    }
]

output_lv = {
    'X': (1, 12),
    'name': 'Evaluation',
    'terms': {
		'Unprofessional': {'umf': ('trapmf', 0, 0, 0.14, 1.97), 'lmf': ('trapmf', 0, 0, 0.05, 0.66, 1)},
        'Irresponsible': {'umf': ('trapmf', 0.59, 1.50, 2.00, 3.41), 'lmf': ('trapmf', 0.79, 1.68, 1.68, 2.21, 0.74)},
        'Satisfactory': {'umf': ('trapmf', 0.59, 2.00, 3.25, 4.41), 'lmf': ('trapmf', 2.29, 2.70, 2.70, 3.21, 0.42)},
        'Average': {'umf': ('trapmf', 1.28, 3.50, 5.50, 7.83), 'lmf': ('trapmf', 3.79, 4.41, 4.41, 4.91, 0.36)},
        'Competent': {'umf': ('trapmf', 2.59, 4.00, 5.50, 7.62), 'lmf': ('trapmf', 4.29, 4.75, 4.75, 5.21, 0.38)},
        'Effective': {'umf': ('trapmf', 3.38, 5.50, 7.50, 9.62), 'lmf': ('trapmf', 5.79, 6.50, 6.50, 7.21, 0.41)},
        'Highly Qualified': {'umf': ('trapmf', 4.38, 6.50, 8.25, 9.62), 'lmf': ('trapmf', 7.19, 7.58, 8.21, 9.21, 0.37)},
        'Expert': {'umf': ('trapmf', 5.98, 7.75, 8.60, 9.52), 'lmf': ('trapmf', 8.03, 8.37, 8.57, 9.17, 0.57)},
        'Exceptional': {'umf': ('trapmf', 8.68, 9.91, 10, 10), 'lmf': ('trapmf', 9.61, 9.97, 10, 10, 1)},
    }
}

rule_base = [
	(('Ineffective', 'Inadequate', 'Lack', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Lack', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Lack', 'Exceptional'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Limited', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Limited', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Limited', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Limited', 'Exceptional'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Moderate', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Moderate', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Moderate', 'Exceptional'), 'Irresponsible'),
	(('Ineffective', 'Inadequate', 'Effective', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Effective', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Effective', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Effective', 'Exceptional'), 'Irresponsible'),
	(('Ineffective', 'Inadequate', 'Strong', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Strong', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Strong', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Inadequate', 'Strong', 'Exceptional'), 'Satisfactory'),
	(('Ineffective', 'Inadequate', 'Exceptional', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Exceptional', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Inadequate', 'Exceptional', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Inadequate', 'Exceptional', 'Exceptional'), 'Average'),
	(('Ineffective', 'Basic', 'Lack', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Lack', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Lack', 'Exceptional'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Limited', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Limited', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Limited', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Limited', 'Exceptional'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Moderate', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Moderate', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Moderate', 'Exceptional'), 'Satisfactory'),
	(('Ineffective', 'Basic', 'Effective', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Effective', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Effective', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Effective', 'Exceptional'), 'Satisfactory'),
	(('Ineffective', 'Basic', 'Strong', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Strong', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Strong', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Basic', 'Strong', 'Exceptional'), 'Average'),
	(('Ineffective', 'Basic', 'Exceptional', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Basic', 'Exceptional', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Basic', 'Exceptional', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Basic', 'Exceptional', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Competent', 'Lack', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Lack', 'Good'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Lack', 'Exceptional'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Limited', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Limited', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Limited', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Limited', 'Exceptional'), 'Satisfactory'),
	(('Ineffective', 'Competent', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Moderate', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Moderate', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Moderate', 'Exceptional'), 'Average'),
	(('Ineffective', 'Competent', 'Effective', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Competent', 'Effective', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Effective', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Competent', 'Effective', 'Exceptional'), 'Average'),
	(('Ineffective', 'Competent', 'Strong', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Strong', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Strong', 'Good'), 'Average'),
	(('Ineffective', 'Competent', 'Strong', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Competent', 'Exceptional', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Competent', 'Exceptional', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Competent', 'Exceptional', 'Good'), 'Average'),
	(('Ineffective', 'Competent', 'Exceptional', 'Exceptional'), 'Effective'),
	(('Ineffective', 'Advanced', 'Lack', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Advanced', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Ineffective', 'Advanced', 'Lack', 'Good'), 'Irresponsible'),
	(('Ineffective', 'Advanced', 'Lack', 'Exceptional'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Limited', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Advanced', 'Limited', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Advanced', 'Limited', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Limited', 'Exceptional'), 'Average'),
	(('Ineffective', 'Advanced', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Advanced', 'Moderate', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Advanced', 'Moderate', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Moderate', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Advanced', 'Effective', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Advanced', 'Effective', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Effective', 'Good'), 'Average'),
	(('Ineffective', 'Advanced', 'Effective', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Advanced', 'Strong', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Advanced', 'Strong', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Strong', 'Good'), 'Competent'),
	(('Ineffective', 'Advanced', 'Strong', 'Exceptional'), 'Effective'),
	(('Ineffective', 'Advanced', 'Exceptional', 'Limited'), 'Satisfactory'),
	(('Ineffective', 'Advanced', 'Exceptional', 'Moderate'), 'Average'),
	(('Ineffective', 'Advanced', 'Exceptional', 'Good'), 'Competent'),
	(('Ineffective', 'Advanced', 'Exceptional', 'Exceptional'), 'Highly Qualified'),
	(('Ineffective', 'Expert', 'Lack', 'Limited'), 'Unprofessional'),
	(('Ineffective', 'Expert', 'Lack', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Expert', 'Lack', 'Good'), 'Satisfactory'),
	(('Ineffective', 'Expert', 'Lack', 'Exceptional'), 'Average'),
	(('Ineffective', 'Expert', 'Limited', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Expert', 'Limited', 'Moderate'), 'Irresponsible'),
	(('Ineffective', 'Expert', 'Limited', 'Good'), 'Average'),
	(('Ineffective', 'Expert', 'Limited', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Expert', 'Moderate', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Expert', 'Moderate', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Expert', 'Moderate', 'Good'), 'Average'),
	(('Ineffective', 'Expert', 'Moderate', 'Exceptional'), 'Effective'),
	(('Ineffective', 'Expert', 'Effective', 'Limited'), 'Satisfactory'),
	(('Ineffective', 'Expert', 'Effective', 'Moderate'), 'Average'),
	(('Ineffective', 'Expert', 'Effective', 'Good'), 'Competent'),
	(('Ineffective', 'Expert', 'Effective', 'Exceptional'), 'Effective'),
	(('Ineffective', 'Expert', 'Strong', 'Limited'), 'Satisfactory'),
	(('Ineffective', 'Expert', 'Strong', 'Moderate'), 'Average'),
	(('Ineffective', 'Expert', 'Strong', 'Good'), 'Effective'),
	(('Ineffective', 'Expert', 'Strong', 'Exceptional'), 'Highly Qualified'),
	(('Ineffective', 'Expert', 'Exceptional', 'Limited'), 'Average'),
	(('Ineffective', 'Expert', 'Exceptional', 'Moderate'), 'Competent'),
	(('Ineffective', 'Expert', 'Exceptional', 'Good'), 'Effective'),
	(('Ineffective', 'Expert', 'Exceptional', 'Exceptional'), 'Expert'),
	(('Ineffective', 'Professional', 'Lack', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Professional', 'Lack', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Professional', 'Lack', 'Good'), 'Average'),
	(('Ineffective', 'Professional', 'Lack', 'Exceptional'), 'Competent'),
	(('Ineffective', 'Professional', 'Limited', 'Limited'), 'Irresponsible'),
	(('Ineffective', 'Professional', 'Limited', 'Moderate'), 'Satisfactory'),
	(('Ineffective', 'Professional', 'Limited', 'Good'), 'Competent'),
	(('Ineffective', 'Professional', 'Limited', 'Exceptional'), 'Effective'),
	(('Ineffective', 'Professional', 'Moderate', 'Limited'), 'Satisfactory'),
	(('Ineffective', 'Professional', 'Moderate', 'Moderate'), 'Average'),
	(('Ineffective', 'Professional', 'Moderate', 'Good'), 'Competent'),
	(('Ineffective', 'Professional', 'Moderate', 'Exceptional'), 'Highly Qualified'),
	(('Ineffective', 'Professional', 'Effective', 'Limited'), 'Average'),
	(('Ineffective', 'Professional', 'Effective', 'Moderate'), 'Competent'),
	(('Ineffective', 'Professional', 'Effective', 'Good'), 'Effective'),
	(('Ineffective', 'Professional', 'Effective', 'Exceptional'), 'Highly Qualified'),
	(('Ineffective', 'Professional', 'Strong', 'Limited'), 'Average'),
	(('Ineffective', 'Professional', 'Strong', 'Moderate'), 'Competent'),
	(('Ineffective', 'Professional', 'Strong', 'Good'), 'Highly Qualified'),
	(('Ineffective', 'Professional', 'Strong', 'Exceptional'), 'Expert'),
	(('Ineffective', 'Professional', 'Exceptional', 'Limited'), 'Competent'),
	(('Ineffective', 'Professional', 'Exceptional', 'Moderate'), 'Effective'),
	(('Ineffective', 'Professional', 'Exceptional', 'Good'), 'Highly Qualified'),
	(('Ineffective', 'Professional', 'Exceptional', 'Exceptional'), 'Expert'),
	(('Average', 'Inadequate', 'Lack', 'Limited'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Lack', 'Good'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Lack', 'Exceptional'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Limited', 'Limited'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Limited', 'Moderate'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Limited', 'Good'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Limited', 'Exceptional'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Moderate', 'Moderate'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Moderate', 'Good'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Moderate', 'Exceptional'), 'Satisfactory'),
	(('Average', 'Inadequate', 'Effective', 'Limited'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Effective', 'Moderate'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Effective', 'Good'), 'Satisfactory'),
	(('Average', 'Inadequate', 'Effective', 'Exceptional'), 'Average'),
	(('Average', 'Inadequate', 'Strong', 'Limited'), 'Unprofessional'),
	(('Average', 'Inadequate', 'Strong', 'Moderate'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Strong', 'Good'), 'Satisfactory'),
	(('Average', 'Inadequate', 'Strong', 'Exceptional'), 'Average'),
	(('Average', 'Inadequate', 'Exceptional', 'Limited'), 'Irresponsible'),
	(('Average', 'Inadequate', 'Exceptional', 'Moderate'), 'Satisfactory'),
	(('Average', 'Inadequate', 'Exceptional', 'Good'), 'Average'),
	(('Average', 'Inadequate', 'Exceptional', 'Exceptional'), 'Competent'),
	(('Average', 'Basic', 'Lack', 'Limited'), 'Unprofessional'),
	(('Average', 'Basic', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Average', 'Basic', 'Lack', 'Good'), 'Irresponsible'),
	(('Average', 'Basic', 'Lack', 'Exceptional'), 'Satisfactory'),
	(('Average', 'Basic', 'Limited', 'Limited'), 'Unprofessional'),
	(('Average', 'Basic', 'Limited', 'Moderate'), 'Unprofessional'),
	(('Average', 'Basic', 'Limited', 'Good'), 'Irresponsible'),
	(('Average', 'Basic', 'Limited', 'Exceptional'), 'Satisfactory'),
	(('Average', 'Basic', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Average', 'Basic', 'Moderate', 'Moderate'), 'Irresponsible'),
	(('Average', 'Basic', 'Moderate', 'Good'), 'Satisfactory'),
	(('Average', 'Basic', 'Moderate', 'Exceptional'), 'Average'),
	(('Average', 'Basic', 'Effective', 'Limited'), 'Unprofessional'),
	(('Average', 'Basic', 'Effective', 'Moderate'), 'Irresponsible'),
	(('Average', 'Basic', 'Effective', 'Good'), 'Average'),
	(('Average', 'Basic', 'Effective', 'Exceptional'), 'Competent'),
	(('Average', 'Basic', 'Strong', 'Limited'), 'Irresponsible'),
	(('Average', 'Basic', 'Strong', 'Moderate'), 'Satisfactory'),
	(('Average', 'Basic', 'Strong', 'Good'), 'Average'),
	(('Average', 'Basic', 'Strong', 'Exceptional'), 'Competent'),
	(('Average', 'Basic', 'Exceptional', 'Limited'), 'Irresponsible'),
	(('Average', 'Basic', 'Exceptional', 'Moderate'), 'Average'),
	(('Average', 'Basic', 'Exceptional', 'Good'), 'Competent'),
	(('Average', 'Basic', 'Exceptional', 'Exceptional'), 'Effective'),
	(('Average', 'Competent', 'Lack', 'Limited'), 'Unprofessional'),
	(('Average', 'Competent', 'Lack', 'Moderate'), 'Irresponsible'),
	(('Average', 'Competent', 'Lack', 'Good'), 'Satisfactory'),
	(('Average', 'Competent', 'Lack', 'Exceptional'), 'Average'),
	(('Average', 'Competent', 'Limited', 'Limited'), 'Unprofessional'),
	(('Average', 'Competent', 'Limited', 'Moderate'), 'Irresponsible'),
	(('Average', 'Competent', 'Limited', 'Good'), 'Satisfactory'),
	(('Average', 'Competent', 'Limited', 'Exceptional'), 'Average'),
	(('Average', 'Competent', 'Moderate', 'Limited'), 'Irresponsible'),
	(('Average', 'Competent', 'Moderate', 'Moderate'), 'Satisfactory'),
	(('Average', 'Competent', 'Moderate', 'Good'), 'Average'),
	(('Average', 'Competent', 'Moderate', 'Exceptional'), 'Competent'),
	(('Average', 'Competent', 'Effective', 'Limited'), 'Irresponsible'),
	(('Average', 'Competent', 'Effective', 'Moderate'), 'Satisfactory'),
	(('Average', 'Competent', 'Effective', 'Good'), 'Competent'),
	(('Average', 'Competent', 'Effective', 'Exceptional'), 'Effective'),
	(('Average', 'Competent', 'Strong', 'Limited'), 'Satisfactory'),
	(('Average', 'Competent', 'Strong', 'Moderate'), 'Average'),
	(('Average', 'Competent', 'Strong', 'Good'), 'Competent'),
	(('Average', 'Competent', 'Strong', 'Exceptional'), 'Effective'),
	(('Average', 'Competent', 'Exceptional', 'Limited'), 'Satisfactory'),
	(('Average', 'Competent', 'Exceptional', 'Moderate'), 'Competent'),
	(('Average', 'Competent', 'Exceptional', 'Good'), 'Effective'),
	(('Average', 'Competent', 'Exceptional', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Advanced', 'Lack', 'Limited'), 'Unprofessional'),
	(('Average', 'Advanced', 'Lack', 'Moderate'), 'Irresponsible'),
	(('Average', 'Advanced', 'Lack', 'Good'), 'Average'),
	(('Average', 'Advanced', 'Lack', 'Exceptional'), 'Competent'),
	(('Average', 'Advanced', 'Limited', 'Limited'), 'Irresponsible'),
	(('Average', 'Advanced', 'Limited', 'Moderate'), 'Satisfactory'),
	(('Average', 'Advanced', 'Limited', 'Good'), 'Average'),
	(('Average', 'Advanced', 'Limited', 'Exceptional'), 'Competent'),
	(('Average', 'Advanced', 'Moderate', 'Limited'), 'Irresponsible'),
	(('Average', 'Advanced', 'Moderate', 'Moderate'), 'Average'),
	(('Average', 'Advanced', 'Moderate', 'Good'), 'Competent'),
	(('Average', 'Advanced', 'Moderate', 'Exceptional'), 'Effective'),
	(('Average', 'Advanced', 'Effective', 'Limited'), 'Satisfactory'),
	(('Average', 'Advanced', 'Effective', 'Moderate'), 'Average'),
	(('Average', 'Advanced', 'Effective', 'Good'), 'Effective'),
	(('Average', 'Advanced', 'Effective', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Advanced', 'Strong', 'Limited'), 'Average'),
	(('Average', 'Advanced', 'Strong', 'Moderate'), 'Competent'),
	(('Average', 'Advanced', 'Strong', 'Good'), 'Effective'),
	(('Average', 'Advanced', 'Strong', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Advanced', 'Exceptional', 'Limited'), 'Average'),
	(('Average', 'Advanced', 'Exceptional', 'Moderate'), 'Effective'),
	(('Average', 'Advanced', 'Exceptional', 'Good'), 'Highly Qualified'),
	(('Average', 'Advanced', 'Exceptional', 'Exceptional'), 'Expert'),
	(('Average', 'Expert', 'Lack', 'Limited'), 'Irresponsible'),
	(('Average', 'Expert', 'Lack', 'Moderate'), 'Satisfactory'),
	(('Average', 'Expert', 'Lack', 'Good'), 'Competent'),
	(('Average', 'Expert', 'Lack', 'Exceptional'), 'Effective'),
	(('Average', 'Expert', 'Limited', 'Limited'), 'Satisfactory'),
	(('Average', 'Expert', 'Limited', 'Moderate'), 'Average'),
	(('Average', 'Expert', 'Limited', 'Good'), 'Competent'),
	(('Average', 'Expert', 'Limited', 'Exceptional'), 'Effective'),
	(('Average', 'Expert', 'Moderate', 'Limited'), 'Satisfactory'),
	(('Average', 'Expert', 'Moderate', 'Moderate'), 'Competent'),
	(('Average', 'Expert', 'Moderate', 'Good'), 'Effective'),
	(('Average', 'Expert', 'Moderate', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Expert', 'Effective', 'Limited'), 'Average'),
	(('Average', 'Expert', 'Effective', 'Moderate'), 'Competent'),
	(('Average', 'Expert', 'Effective', 'Good'), 'Highly Qualified'),
	(('Average', 'Expert', 'Effective', 'Exceptional'), 'Expert'),
	(('Average', 'Expert', 'Strong', 'Limited'), 'Competent'),
	(('Average', 'Expert', 'Strong', 'Moderate'), 'Effective'),
	(('Average', 'Expert', 'Strong', 'Good'), 'Highly Qualified'),
	(('Average', 'Expert', 'Strong', 'Exceptional'), 'Expert'),
	(('Average', 'Expert', 'Exceptional', 'Limited'), 'Competent'),
	(('Average', 'Expert', 'Exceptional', 'Moderate'), 'Highly Qualified'),
	(('Average', 'Expert', 'Exceptional', 'Good'), 'Expert'),
	(('Average', 'Expert', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Average', 'Professional', 'Lack', 'Limited'), 'Satisfactory'),
	(('Average', 'Professional', 'Lack', 'Moderate'), 'Average'),
	(('Average', 'Professional', 'Lack', 'Good'), 'Effective'),
	(('Average', 'Professional', 'Lack', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Professional', 'Limited', 'Limited'), 'Average'),
	(('Average', 'Professional', 'Limited', 'Moderate'), 'Competent'),
	(('Average', 'Professional', 'Limited', 'Good'), 'Effective'),
	(('Average', 'Professional', 'Limited', 'Exceptional'), 'Highly Qualified'),
	(('Average', 'Professional', 'Moderate', 'Limited'), 'Average'),
	(('Average', 'Professional', 'Moderate', 'Moderate'), 'Effective'),
	(('Average', 'Professional', 'Moderate', 'Good'), 'Highly Qualified'),
	(('Average', 'Professional', 'Moderate', 'Exceptional'), 'Expert'),
	(('Average', 'Professional', 'Effective', 'Limited'), 'Competent'),
	(('Average', 'Professional', 'Effective', 'Moderate'), 'Effective'),
	(('Average', 'Professional', 'Effective', 'Good'), 'Highly Qualified'),
	(('Average', 'Professional', 'Effective', 'Exceptional'), 'Expert'),
	(('Average', 'Professional', 'Strong', 'Limited'), 'Effective'),
	(('Average', 'Professional', 'Strong', 'Moderate'), 'Highly Qualified'),
	(('Average', 'Professional', 'Strong', 'Good'), 'Expert'),
	(('Average', 'Professional', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Average', 'Professional', 'Exceptional', 'Limited'), 'Effective'),
	(('Average', 'Professional', 'Exceptional', 'Moderate'), 'Highly Qualified'),
	(('Average', 'Professional', 'Exceptional', 'Good'), 'Expert'),
	(('Average', 'Professional', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Inadequate', 'Lack', 'Limited'), 'Unprofessional'),
	(('Effective', 'Inadequate', 'Lack', 'Moderate'), 'Unprofessional'),
	(('Effective', 'Inadequate', 'Lack', 'Good'), 'Irresponsible'),
	(('Effective', 'Inadequate', 'Lack', 'Exceptional'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Limited', 'Limited'), 'Unprofessional'),
	(('Effective', 'Inadequate', 'Limited', 'Moderate'), 'Irresponsible'),
	(('Effective', 'Inadequate', 'Limited', 'Good'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Limited', 'Exceptional'), 'Average'),
	(('Effective', 'Inadequate', 'Moderate', 'Limited'), 'Unprofessional'),
	(('Effective', 'Inadequate', 'Moderate', 'Moderate'), 'Irresponsible'),
	(('Effective', 'Inadequate', 'Moderate', 'Good'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Moderate', 'Exceptional'), 'Competent'),
	(('Effective', 'Inadequate', 'Effective', 'Limited'), 'Irresponsible'),
	(('Effective', 'Inadequate', 'Effective', 'Moderate'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Effective', 'Good'), 'Average'),
	(('Effective', 'Inadequate', 'Effective', 'Exceptional'), 'Competent'),
	(('Effective', 'Inadequate', 'Strong', 'Limited'), 'Irresponsible'),
	(('Effective', 'Inadequate', 'Strong', 'Moderate'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Strong', 'Good'), 'Competent'),
	(('Effective', 'Inadequate', 'Strong', 'Exceptional'), 'Effective'),
	(('Effective', 'Inadequate', 'Exceptional', 'Limited'), 'Satisfactory'),
	(('Effective', 'Inadequate', 'Exceptional', 'Moderate'), 'Average'),
	(('Effective', 'Inadequate', 'Exceptional', 'Good'), 'Competent'),
	(('Effective', 'Inadequate', 'Exceptional', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Basic', 'Lack', 'Limited'), 'Unprofessional'),
	(('Effective', 'Basic', 'Lack', 'Moderate'), 'Irresponsible'),
	(('Effective', 'Basic', 'Lack', 'Good'), 'Satisfactory'),
	(('Effective', 'Basic', 'Lack', 'Exceptional'), 'Average'),
	(('Effective', 'Basic', 'Limited', 'Limited'), 'Unprofessional'),
	(('Effective', 'Basic', 'Limited', 'Moderate'), 'Irresponsible'),
	(('Effective', 'Basic', 'Limited', 'Good'), 'Average'),
	(('Effective', 'Basic', 'Limited', 'Exceptional'), 'Competent'),
	(('Effective', 'Basic', 'Moderate', 'Limited'), 'Irresponsible'),
	(('Effective', 'Basic', 'Moderate', 'Moderate'), 'Satisfactory'),
	(('Effective', 'Basic', 'Moderate', 'Good'), 'Average'),
	(('Effective', 'Basic', 'Moderate', 'Exceptional'), 'Effective'),
	(('Effective', 'Basic', 'Effective', 'Limited'), 'Irresponsible'),
	(('Effective', 'Basic', 'Effective', 'Moderate'), 'Average'),
	(('Effective', 'Basic', 'Effective', 'Good'), 'Competent'),
	(('Effective', 'Basic', 'Effective', 'Exceptional'), 'Effective'),
	(('Effective', 'Basic', 'Strong', 'Limited'), 'Satisfactory'),
	(('Effective', 'Basic', 'Strong', 'Moderate'), 'Average'),
	(('Effective', 'Basic', 'Strong', 'Good'), 'Effective'),
	(('Effective', 'Basic', 'Strong', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Basic', 'Exceptional', 'Limited'), 'Average'),
	(('Effective', 'Basic', 'Exceptional', 'Moderate'), 'Competent'),
	(('Effective', 'Basic', 'Exceptional', 'Good'), 'Effective'),
	(('Effective', 'Basic', 'Exceptional', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Competent', 'Lack', 'Limited'), 'Irresponsible'),
	(('Effective', 'Competent', 'Lack', 'Moderate'), 'Satisfactory'),
	(('Effective', 'Competent', 'Lack', 'Good'), 'Average'),
	(('Effective', 'Competent', 'Lack', 'Exceptional'), 'Competent'),
	(('Effective', 'Competent', 'Limited', 'Limited'), 'Irresponsible'),
	(('Effective', 'Competent', 'Limited', 'Moderate'), 'Satisfactory'),
	(('Effective', 'Competent', 'Limited', 'Good'), 'Competent'),
	(('Effective', 'Competent', 'Limited', 'Exceptional'), 'Effective'),
	(('Effective', 'Competent', 'Moderate', 'Limited'), 'Satisfactory'),
	(('Effective', 'Competent', 'Moderate', 'Moderate'), 'Average'),
	(('Effective', 'Competent', 'Moderate', 'Good'), 'Competent'),
	(('Effective', 'Competent', 'Moderate', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Competent', 'Effective', 'Limited'), 'Satisfactory'),
	(('Effective', 'Competent', 'Effective', 'Moderate'), 'Competent'),
	(('Effective', 'Competent', 'Effective', 'Good'), 'Effective'),
	(('Effective', 'Competent', 'Effective', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Competent', 'Strong', 'Limited'), 'Average'),
	(('Effective', 'Competent', 'Strong', 'Moderate'), 'Competent'),
	(('Effective', 'Competent', 'Strong', 'Good'), 'Highly Qualified'),
	(('Effective', 'Competent', 'Strong', 'Exceptional'), 'Expert'),
	(('Effective', 'Competent', 'Exceptional', 'Limited'), 'Competent'),
	(('Effective', 'Competent', 'Exceptional', 'Moderate'), 'Effective'),
	(('Effective', 'Competent', 'Exceptional', 'Good'), 'Highly Qualified'),
	(('Effective', 'Competent', 'Exceptional', 'Exceptional'), 'Expert'),
	(('Effective', 'Advanced', 'Lack', 'Limited'), 'Irresponsible'),
	(('Effective', 'Advanced', 'Lack', 'Moderate'), 'Average'),
	(('Effective', 'Advanced', 'Lack', 'Good'), 'Competent'),
	(('Effective', 'Advanced', 'Lack', 'Exceptional'), 'Effective'),
	(('Effective', 'Advanced', 'Limited', 'Limited'), 'Satisfactory'),
	(('Effective', 'Advanced', 'Limited', 'Moderate'), 'Average'),
	(('Effective', 'Advanced', 'Limited', 'Good'), 'Effective'),
	(('Effective', 'Advanced', 'Limited', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Advanced', 'Moderate', 'Limited'), 'Average'),
	(('Effective', 'Advanced', 'Moderate', 'Moderate'), 'Competent'),
	(('Effective', 'Advanced', 'Moderate', 'Good'), 'Effective'),
	(('Effective', 'Advanced', 'Moderate', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Advanced', 'Effective', 'Limited'), 'Average'),
	(('Effective', 'Advanced', 'Effective', 'Moderate'), 'Effective'),
	(('Effective', 'Advanced', 'Effective', 'Good'), 'Highly Qualified'),
	(('Effective', 'Advanced', 'Effective', 'Exceptional'), 'Expert'),
	(('Effective', 'Advanced', 'Strong', 'Limited'), 'Competent'),
	(('Effective', 'Advanced', 'Strong', 'Moderate'), 'Effective'),
	(('Effective', 'Advanced', 'Strong', 'Good'), 'Expert'),
	(('Effective', 'Advanced', 'Strong', 'Exceptional'), 'Expert'),
	(('Effective', 'Advanced', 'Exceptional', 'Limited'), 'Effective'),
	(('Effective', 'Advanced', 'Exceptional', 'Moderate'), 'Highly Qualified'),
	(('Effective', 'Advanced', 'Exceptional', 'Good'), 'Expert'),
	(('Effective', 'Advanced', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Expert', 'Lack', 'Limited'), 'Satisfactory'),
	(('Effective', 'Expert', 'Lack', 'Moderate'), 'Competent'),
	(('Effective', 'Expert', 'Lack', 'Good'), 'Effective'),
	(('Effective', 'Expert', 'Lack', 'Exceptional'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Limited', 'Limited'), 'Average'),
	(('Effective', 'Expert', 'Limited', 'Moderate'), 'Competent'),
	(('Effective', 'Expert', 'Limited', 'Good'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Limited', 'Exceptional'), 'Expert'),
	(('Effective', 'Expert', 'Moderate', 'Limited'), 'Competent'),
	(('Effective', 'Expert', 'Moderate', 'Moderate'), 'Effective'),
	(('Effective', 'Expert', 'Moderate', 'Good'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Moderate', 'Exceptional'), 'Expert'),
	(('Effective', 'Expert', 'Effective', 'Limited'), 'Competent'),
	(('Effective', 'Expert', 'Effective', 'Moderate'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Effective', 'Good'), 'Expert'),
	(('Effective', 'Expert', 'Effective', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Expert', 'Strong', 'Limited'), 'Effective'),
	(('Effective', 'Expert', 'Strong', 'Moderate'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Strong', 'Good'), 'Expert'),
	(('Effective', 'Expert', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Expert', 'Exceptional', 'Limited'), 'Highly Qualified'),
	(('Effective', 'Expert', 'Exceptional', 'Moderate'), 'Expert'),
	(('Effective', 'Expert', 'Exceptional', 'Good'), 'Exceptional'),
	(('Effective', 'Expert', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Professional', 'Lack', 'Limited'), 'Average'),
	(('Effective', 'Professional', 'Lack', 'Moderate'), 'Effective'),
	(('Effective', 'Professional', 'Lack', 'Good'), 'Highly Qualified'),
	(('Effective', 'Professional', 'Lack', 'Exceptional'), 'Expert'),
	(('Effective', 'Professional', 'Limited', 'Limited'), 'Competent'),
	(('Effective', 'Professional', 'Limited', 'Moderate'), 'Effective'),
	(('Effective', 'Professional', 'Limited', 'Good'), 'Expert'),
	(('Effective', 'Professional', 'Limited', 'Exceptional'), 'Expert'),
	(('Effective', 'Professional', 'Moderate', 'Limited'), 'Effective'),
	(('Effective', 'Professional', 'Moderate', 'Moderate'), 'Highly Qualified'),
	(('Effective', 'Professional', 'Moderate', 'Good'), 'Expert'),
	(('Effective', 'Professional', 'Moderate', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Professional', 'Effective', 'Limited'), 'Effective'),
	(('Effective', 'Professional', 'Effective', 'Moderate'), 'Expert'),
	(('Effective', 'Professional', 'Effective', 'Good'), 'Exceptional'),
	(('Effective', 'Professional', 'Effective', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Professional', 'Strong', 'Limited'), 'Highly Qualified'),
	(('Effective', 'Professional', 'Strong', 'Moderate'), 'Expert'),
	(('Effective', 'Professional', 'Strong', 'Good'), 'Exceptional'),
	(('Effective', 'Professional', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Effective', 'Professional', 'Exceptional', 'Limited'), 'Expert'),
	(('Effective', 'Professional', 'Exceptional', 'Moderate'), 'Exceptional'),
	(('Effective', 'Professional', 'Exceptional', 'Good'), 'Exceptional'),
	(('Effective', 'Professional', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Inadequate', 'Lack', 'Limited'), 'Unprofessional'),
	(('Exceptional', 'Inadequate', 'Lack', 'Moderate'), 'Irresponsible'),
	(('Exceptional', 'Inadequate', 'Lack', 'Good'), 'Average'),
	(('Exceptional', 'Inadequate', 'Lack', 'Exceptional'), 'Competent'),
	(('Exceptional', 'Inadequate', 'Limited', 'Limited'), 'Irresponsible'),
	(('Exceptional', 'Inadequate', 'Limited', 'Moderate'), 'Satisfactory'),
	(('Exceptional', 'Inadequate', 'Limited', 'Good'), 'Average'),
	(('Exceptional', 'Inadequate', 'Limited', 'Exceptional'), 'Effective'),
	(('Exceptional', 'Inadequate', 'Moderate', 'Limited'), 'Irresponsible'),
	(('Exceptional', 'Inadequate', 'Moderate', 'Moderate'), 'Average'),
	(('Exceptional', 'Inadequate', 'Moderate', 'Good'), 'Competent'),
	(('Exceptional', 'Inadequate', 'Moderate', 'Exceptional'), 'Effective'),
	(('Exceptional', 'Inadequate', 'Effective', 'Limited'), 'Satisfactory'),
	(('Exceptional', 'Inadequate', 'Effective', 'Moderate'), 'Average'),
	(('Exceptional', 'Inadequate', 'Effective', 'Good'), 'Effective'),
	(('Exceptional', 'Inadequate', 'Effective', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Inadequate', 'Strong', 'Limited'), 'Average'),
	(('Exceptional', 'Inadequate', 'Strong', 'Moderate'), 'Competent'),
	(('Exceptional', 'Inadequate', 'Strong', 'Good'), 'Effective'),
	(('Exceptional', 'Inadequate', 'Strong', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Inadequate', 'Exceptional', 'Limited'), 'Average'),
	(('Exceptional', 'Inadequate', 'Exceptional', 'Moderate'), 'Effective'),
	(('Exceptional', 'Inadequate', 'Exceptional', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Inadequate', 'Exceptional', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Basic', 'Lack', 'Limited'), 'Irresponsible'),
	(('Exceptional', 'Basic', 'Lack', 'Moderate'), 'Satisfactory'),
	(('Exceptional', 'Basic', 'Lack', 'Good'), 'Competent'),
	(('Exceptional', 'Basic', 'Lack', 'Exceptional'), 'Effective'),
	(('Exceptional', 'Basic', 'Limited', 'Limited'), 'Satisfactory'),
	(('Exceptional', 'Basic', 'Limited', 'Moderate'), 'Average'),
	(('Exceptional', 'Basic', 'Limited', 'Good'), 'Competent'),
	(('Exceptional', 'Basic', 'Limited', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Basic', 'Moderate', 'Limited'), 'Satisfactory'),
	(('Exceptional', 'Basic', 'Moderate', 'Moderate'), 'Competent'),
	(('Exceptional', 'Basic', 'Moderate', 'Good'), 'Effective'),
	(('Exceptional', 'Basic', 'Moderate', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Basic', 'Effective', 'Limited'), 'Average'),
	(('Exceptional', 'Basic', 'Effective', 'Moderate'), 'Competent'),
	(('Exceptional', 'Basic', 'Effective', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Basic', 'Effective', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Basic', 'Strong', 'Limited'), 'Competent'),
	(('Exceptional', 'Basic', 'Strong', 'Moderate'), 'Effective'),
	(('Exceptional', 'Basic', 'Strong', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Basic', 'Strong', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Basic', 'Exceptional', 'Limited'), 'Competent'),
	(('Exceptional', 'Basic', 'Exceptional', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Basic', 'Exceptional', 'Good'), 'Expert'),
	(('Exceptional', 'Basic', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Competent', 'Lack', 'Limited'), 'Satisfactory'),
	(('Exceptional', 'Competent', 'Lack', 'Moderate'), 'Average'),
	(('Exceptional', 'Competent', 'Lack', 'Good'), 'Effective'),
	(('Exceptional', 'Competent', 'Lack', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Limited', 'Limited'), 'Average'),
	(('Exceptional', 'Competent', 'Limited', 'Moderate'), 'Competent'),
	(('Exceptional', 'Competent', 'Limited', 'Good'), 'Effective'),
	(('Exceptional', 'Competent', 'Limited', 'Exceptional'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Moderate', 'Limited'), 'Average'),
	(('Exceptional', 'Competent', 'Moderate', 'Moderate'), 'Effective'),
	(('Exceptional', 'Competent', 'Moderate', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Moderate', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Competent', 'Effective', 'Limited'), 'Competent'),
	(('Exceptional', 'Competent', 'Effective', 'Moderate'), 'Effective'),
	(('Exceptional', 'Competent', 'Effective', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Effective', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Competent', 'Strong', 'Limited'), 'Effective'),
	(('Exceptional', 'Competent', 'Strong', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Strong', 'Good'), 'Expert'),
	(('Exceptional', 'Competent', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Competent', 'Exceptional', 'Limited'), 'Effective'),
	(('Exceptional', 'Competent', 'Exceptional', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Competent', 'Exceptional', 'Good'), 'Expert'),
	(('Exceptional', 'Competent', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Lack', 'Limited'), 'Average'),
	(('Exceptional', 'Advanced', 'Lack', 'Moderate'), 'Competent'),
	(('Exceptional', 'Advanced', 'Lack', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Lack', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Advanced', 'Limited', 'Limited'), 'Competent'),
	(('Exceptional', 'Advanced', 'Limited', 'Moderate'), 'Effective'),
	(('Exceptional', 'Advanced', 'Limited', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Limited', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Advanced', 'Moderate', 'Limited'), 'Competent'),
	(('Exceptional', 'Advanced', 'Moderate', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Moderate', 'Good'), 'Expert'),
	(('Exceptional', 'Advanced', 'Moderate', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Effective', 'Limited'), 'Effective'),
	(('Exceptional', 'Advanced', 'Effective', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Effective', 'Good'), 'Expert'),
	(('Exceptional', 'Advanced', 'Effective', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Strong', 'Limited'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Strong', 'Moderate'), 'Expert'),
	(('Exceptional', 'Advanced', 'Strong', 'Good'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Exceptional', 'Limited'), 'Highly Qualified'),
	(('Exceptional', 'Advanced', 'Exceptional', 'Moderate'), 'Expert'),
	(('Exceptional', 'Advanced', 'Exceptional', 'Good'), 'Exceptional'),
	(('Exceptional', 'Advanced', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Lack', 'Limited'), 'Competent'),
	(('Exceptional', 'Expert', 'Lack', 'Moderate'), 'Effective'),
	(('Exceptional', 'Expert', 'Lack', 'Good'), 'Highly Qualified'),
	(('Exceptional', 'Expert', 'Lack', 'Exceptional'), 'Expert'),
	(('Exceptional', 'Expert', 'Limited', 'Limited'), 'Effective'),
	(('Exceptional', 'Expert', 'Limited', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Expert', 'Limited', 'Good'), 'Expert'),
	(('Exceptional', 'Expert', 'Limited', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Moderate', 'Limited'), 'Effective'),
	(('Exceptional', 'Expert', 'Moderate', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Expert', 'Moderate', 'Good'), 'Expert'),
	(('Exceptional', 'Expert', 'Moderate', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Effective', 'Limited'), 'Highly Qualified'),
	(('Exceptional', 'Expert', 'Effective', 'Moderate'), 'Expert'),
	(('Exceptional', 'Expert', 'Effective', 'Good'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Effective', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Strong', 'Limited'), 'Expert'),
	(('Exceptional', 'Expert', 'Strong', 'Moderate'), 'Expert'),
	(('Exceptional', 'Expert', 'Strong', 'Good'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Exceptional', 'Limited'), 'Expert'),
	(('Exceptional', 'Expert', 'Exceptional', 'Moderate'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Exceptional', 'Good'), 'Exceptional'),
	(('Exceptional', 'Expert', 'Exceptional', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Lack', 'Limited'), 'Effective'),
	(('Exceptional', 'Professional', 'Lack', 'Moderate'), 'Highly Qualified'),
	(('Exceptional', 'Professional', 'Lack', 'Good'), 'Expert'),
	(('Exceptional', 'Professional', 'Lack', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Limited', 'Limited'), 'Highly Qualified'),
	(('Exceptional', 'Professional', 'Limited', 'Moderate'), 'Expert'),
	(('Exceptional', 'Professional', 'Limited', 'Good'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Limited', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Moderate', 'Limited'), 'Highly Qualified'),
	(('Exceptional', 'Professional', 'Moderate', 'Moderate'), 'Expert'),
	(('Exceptional', 'Professional', 'Moderate', 'Good'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Moderate', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Effective', 'Limited'), 'Expert'),
	(('Exceptional', 'Professional', 'Effective', 'Moderate'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Effective', 'Good'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Effective', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Strong', 'Limited'), 'Expert'),
	(('Exceptional', 'Professional', 'Strong', 'Moderate'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Strong', 'Good'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Strong', 'Exceptional'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Exceptional', 'Limited'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Exceptional', 'Moderate'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Exceptional', 'Good'), 'Exceptional'),
	(('Exceptional', 'Professional', 'Exceptional', 'Exceptional'), 'Exceptional')
]